# Generated by Django 6.0.3 on 2026-03-31 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_zu', models.CharField(blank=True, max_length=100)),
                ('name_xh', models.CharField(blank=True, max_length=100)),
                ('name_af', models.CharField(blank=True, max_length=100)),
                ('name_ses', models.CharField(blank=True, max_length=100)),
                ('name_ts', models.CharField(blank=True, max_length=100)),
                ('name_sep', models.CharField(blank=True, max_length=100)),
                ('name_ven', models.CharField(blank=True, max_length=100)),
                ('name_nde', models.CharField(blank=True, max_length=100)),
                ('name_ss', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='fa-solid fa-circle-exclamation', help_text='Font Awesome icon class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='reporting.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('ward', models.CharField(blank=True, help_text='Optional ward number', max_length=20)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_description', models.TextField(help_text='Describe the exact location (building, landmark, etc.)')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/photos/')),
                ('reported_language', models.CharField(choices=[('en', 'English'), ('zu', 'isiZulu'), ('xh', 'isiXhosa'), ('af', 'Afrikaans'), ('ses', 'Sesotho'), ('set', 'Setswana'), ('ss', 'siSwati'), ('ve', 'Tshivenda'), ('ts', 'Xitsonga'), ('nde', 'isiNdebele'), ('sep', 'Sepedi')], default='en', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged by Municipality'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('municipal_reference', models.CharField(blank=True, help_text='Official municipality reference', max_length=100)),
                ('tracking_link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reporting.issuecategory')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reporting.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reporting.province')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(help_text='Resident, Municipality, or System', max_length=100)),
                ('message', models.TextField()),
                ('status_change', models.CharField(blank=True, choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged by Municipality'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show on public dashboard')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reporting.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
